backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "settings"
    label: "Configurações do Site"
    files:
      - label: "Informações Gerais"
        name: "general"
        file: "content/settings/general.json"
        fields:
          - { label: "Nome do Site", name: "site_name", widget: "string" }
          - { label: "Descrição", name: "description", widget: "text" }
          - { label: "Email de Contato", name: "contact_email", widget: "string" }
          - { label: "Telefone", name: "phone", widget: "string" }
          - { label: "Endereço", name: "address", widget: "text" }

  - name: "hero"
    label: "Seção Hero"
    files:
      - label: "Conteúdo Hero"
        name: "hero_content"
        file: "content/hero.json"
        fields:
          - { label: "Título Principal", name: "title", widget: "string" }
          - { label: "Subtítulo", name: "subtitle", widget: "text" }
          - { label: "Texto do Botão", name: "button_text", widget: "string" }
          - { label: "Imagem de Fundo", name: "background_image", widget: "image" }

  - name: "services"
    label: "Serviços"
    files:
      - label: "Lista de Serviços"
        name: "services_list"
        file: "content/services.json"
        fields:
          - { label: "Título da Seção", name: "section_title", widget: "string" }
          - { label: "Descrição da Seção", name: "section_description", widget: "text" }
          - label: "Serviços"
            name: "services"
            widget: "list"
            fields:
              - { label: "Ícone", name: "icon", widget: "string", hint: "Nome do ícone Lucide (ex: Sofa, Armchair)" }
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Descrição", name: "description", widget: "text" }

  - name: "gallery"
    label: "Galeria"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Categoria", name: "category", widget: "select", options: ["Móveis", "Salão", "Cozinha", "Quarto", "Sala"] }
      - { label: "Ordem", name: "order", widget: "number", default: 0 }

  - name: "testimonials"
    label: "Depoimentos"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome do Cliente", name: "name", widget: "string" }
      - { label: "Depoimento", name: "content", widget: "text" }
      - { label: "Avaliação (1-5)", name: "rating", widget: "number", min: 1, max: 5, default: 5 }
      - { label: "Foto (opcional)", name: "photo", widget: "image", required: false }
      - { label: "Cargo/Empresa", name: "role", widget: "string", required: false }

  - name: "pages"
    label: "Páginas"
    files:
      - label: "Página Inicial"
        name: "home"
        file: "content/pages/home.json"
        fields:
          - { label: "Meta Título", name: "meta_title", widget: "string" }
          - { label: "Meta Descrição", name: "meta_description", widget: "text", hint: "Máximo 160 caracteres" }
          - { label: "Palavras-chave", name: "keywords", widget: "list" }
          - { label: "Mostrar Hero", name: "show_hero", widget: "boolean", default: true }
          - { label: "Mostrar Serviços", name: "show_services", widget: "boolean", default: true }
          - { label: "Mostrar Galeria", name: "show_gallery", widget: "boolean", default: true }
          - { label: "Mostrar Contato", name: "show_contact", widget: "boolean", default: true }

  - name: "footer"
    label: "Rodapé"
    files:
      - label: "Conteúdo do Rodapé"
        name: "footer_content"
        file: "content/footer.json"
        fields:
          - { label: "Texto de Copyright", name: "copyright", widget: "string" }
          - label: "Links Rápidos"
            name: "quick_links"
            widget: "list"
            fields:
              - { label: "Texto", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          - label: "Redes Sociais"
            name: "social_links"
            widget: "list"
            fields:
              - { label: "Rede", name: "platform", widget: "select", options: ["Facebook", "Instagram", "LinkedIn", "WhatsApp"] }
              - { label: "URL", name: "url", widget: "string" }
